version: '3.1'

services:
  laravel:
    image: hitalos/laravel
    volumes:
      - .:/var/www
    ports:
      - 80:80
    links:
      - db:mysql

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RO_Play_DataBase_db
      MYSQL_USER: lyrics
      MYSQL_PASSWORD: 77zcfvc6B
    ports:
      - 3306:3306
    volumes:
      - mysql-heva:/var/lib/mysql
      - ./docker/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  mysql-heva:
